INSERT INTO GENEROS(NOMBRE) VALUES('Accion')
INSERT INTO GENEROS(NOMBRE) VALUES('Comedia')
INSERT INTO GENEROS(NOMBRE) VALUES('Drama')
INSERT INTO GENEROS(NOMBRE) VALUES('Terror')
INSERT INTO GENEROS(NOMBRE) VALUES('Fantasia')

INSERT INTO ACTORES(NOMBRE, URL_IMAGEN) VALUES('Hugh Jackman','https://upload.wikimedia.org/wikipedia/commons/7/77/Logan_Japan_Premiere_Red_Carpet-_Hugh_Jackman_%2838445328406%29_%28rotated%29.jpg')
INSERT INTO ACTORES(NOMBRE, URL_IMAGEN) VALUES('Keanu Reeves','https://upload.wikimedia.org/wikipedia/commons/d/d3/Keanu_Reeves_2019.jpg')

INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Pelicula Test1', 1, '2024-01-01');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Pelicula Test2', 3, '2024-01-01');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Pelicula Test3', 2, '2024-01-01');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Pelicula Test4', 1, '2024-01-01');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Pelicula Test5', 3, '2024-01-01');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Pelicula Test6', 2, '2024-01-01');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Pelicula Test7', 3, '2024-01-01');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Pelicula Test8', 1, '2024-01-01');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Pelicula Test9', 2, '2024-01-01');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Pelicula Test10', 1, '2024-01-01');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Pelicula Test11', 3, '2024-01-01');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Pelicula Test12', 1, '2024-01-01');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Pelicula Test13', 2, '2024-01-01');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Pelicula Test14', 1, '2024-01-01');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Pelicula Test15', 2, '2024-01-01');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Pelicula Test16', 3, '2024-01-01');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Pelicula Test17', 1, '2024-01-01');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Pelicula Test18', 2, '2024-01-01');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Pelicula Test19', 2, '2024-01-01');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Pelicula Test20', 1, '2024-01-01');

